import { useEffect, useRef, useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, Check, ChevronRight, Phone, Quote, Star } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Footer, Header, MobileActions } from "@/components/site-layout";

const images = {
  hero: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2200&q=85",
  craft: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=85",
  foundation: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80",
  kitchen: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85",
  flooring: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=80",
  painting: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=1200&q=80",
  basement: "https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=1200&q=80",
  bathroom: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1200&q=80",
  detail: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1500&q=85",
};

const services = [
  ["01", "Foundation Repair", "Structural solutions planned for long-term stability.", images.foundation],
  ["02", "General Contracting", "One experienced team coordinating every moving part.", images.kitchen],
  ["03", "Flooring Installation", "Precise installation with durable, refined finishes.", images.flooring],
  ["04", "Drywall & Painting", "Clean surfaces, crisp lines, and meticulous preparation.", images.painting],
  ["05", "Basement Finishing", "Comfortable living space created from the ground up.", images.basement],
  ["06", "Handyman Services", "Reliable care for repairs, upgrades, and finishing details.", images.detail],
] as const;

export function HomePage() {
  return <><Header overlay /><main>
    <section className="relative min-h-[92svh] overflow-hidden bg-ink text-background">
      <img src={images.hero} alt="Refined modern home interior after renovation" className="absolute inset-0 size-full animate-drift object-cover" fetchPriority="high" />
      <div className="absolute inset-0 bg-gradient-to-r from-ink via-ink/65 to-ink/10" />
      <div className="relative mx-auto flex min-h-[92svh] max-w-[1440px] flex-col justify-end px-5 pb-20 pt-36 lg:px-10 lg:pb-16">
        <div className="max-w-4xl animate-rise">
          <p className="mb-6 flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.18em] text-primary"><span className="h-px w-10 bg-primary" />Home Improvement & Renovation</p>
          <h1 className="text-5xl font-bold leading-[.96] sm:text-6xl md:text-8xl lg:text-[7.2rem]">Built With Precision.<br /><span className="text-background/70">Designed For Living.</span></h1>
          <p className="mt-7 max-w-2xl text-base leading-relaxed text-background/72 md:text-lg">Professional home improvement and renovation backed by 11+ years of craftsmanship and family-owned service.</p>
          <div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/contact">Get a Free Estimate <ArrowRight /></Link></Button><Button asChild size="lg" variant="inverse"><Link to="/projects">Explore Our Work</Link></Button></div>
        </div>
        <a href="#stats" className="absolute bottom-7 right-5 hidden items-center gap-3 text-[10px] font-bold uppercase tracking-[0.18em] text-background/60 md:flex lg:right-10">Scroll to explore <ArrowDown className="size-4 animate-bounce" /></a>
      </div>
    </section>
    <Stats />
    <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-24 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:py-36">
      <div className="relative"><img src={images.craft} alt="Skilled construction professional reviewing project details" className="h-[520px] w-full object-cover lg:h-[680px]" loading="lazy" /><div className="absolute -bottom-5 right-0 bg-primary px-6 py-5 text-primary-foreground"><strong className="block font-display text-4xl">11+</strong><span className="text-[10px] font-bold uppercase tracking-[0.14em]">Years of experience</span></div></div>
      <div className="self-center lg:pl-12"><Eyebrow>About Progress Interior Designs</Eyebrow><Heading>Craftsmanship You Can See.<br />Quality You Can Trust.</Heading><p className="mt-7 max-w-xl leading-7 text-muted-foreground">Since 2014, Progress Interior Designs has helped homeowners transform and protect their spaces with reliable service, skilled execution, and close attention to every detail.</p><div className="my-8 h-px w-20 bg-primary" /><p className="mb-8 max-w-xl leading-7 text-muted-foreground">From structural repairs to complete renovations, we bring one clear standard to every project: do the work properly.</p><Button asChild variant="dark" size="lg"><Link to="/about">Learn More About Us <ArrowRight /></Link></Button></div>
    </section>
    <Services />
    <Featured />
    <WhyUs />
    <Gallery />
    <Process />
    <Testimonials />
    <Emergency />
    <Contact />
    <FAQ />
  </main><Footer /><MobileActions /></>;
}

function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`mb-5 text-[11px] font-bold uppercase tracking-[0.18em] ${light ? "text-primary" : "text-primary"}`}>{children}</p>; }
function Heading({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <h2 className={`text-4xl font-bold leading-[1.04] md:text-6xl ${light ? "text-background" : "text-foreground"}`}>{children}</h2>; }

function Stats() { return <section id="stats" className="bg-ink text-background"><div className="mx-auto grid max-w-[1440px] grid-cols-2 px-5 md:grid-cols-5 lg:px-10">{[["11+","Years Experience"],["1200+","Happy Customers"],["20+","Expert Team"],["4.7","Client Rating"],["24/7","Emergency Service"]].map(([n,l], i) => <div key={l} className={`border-line py-8 md:border-r md:px-7 md:py-11 ${i === 4 ? "md:border-r-0" : ""}`}><strong className="block font-display text-4xl font-bold text-primary lg:text-5xl">{n}</strong><span className="mt-2 block text-[10px] font-semibold uppercase tracking-[0.14em] text-background/55">{l}</span></div>)}</div></section>; }

function Services() { return <section className="bg-background py-24 lg:py-36"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="mb-14 grid gap-7 lg:grid-cols-2"><div><Eyebrow>Our Expertise</Eyebrow><Heading>Home Improvement,<br />Done Right.</Heading></div><p className="max-w-lg self-end leading-7 text-muted-foreground">From repairs to complete renovations, our experienced team handles every detail.</p></div><div className="grid gap-px bg-border md:grid-cols-2 lg:grid-cols-3">{services.map(([n,title,desc,img], i) => <article key={title} className={`group relative min-h-[390px] overflow-hidden bg-ink ${i === 1 || i === 5 ? "lg:translate-y-8" : ""}`}><img src={img} alt={`${title} work by Progress Interior Designs`} className="absolute inset-0 size-full object-cover opacity-55 transition duration-500 group-hover:scale-105 group-hover:opacity-40" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-background"><span className="text-xs font-bold text-primary">{n}</span><h3 className="mt-3 text-2xl font-bold transition-transform duration-300 group-hover:-translate-y-1">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-background/65">{desc}</p><ArrowRight className="mt-5 text-primary transition-transform duration-300 group-hover:translate-x-2" /></div></article>)}</div><div className="mt-16 text-right"><Button asChild variant="dark"><Link to="/services">Explore All Services <ArrowRight /></Link></Button></div></div></section>; }

function Featured() { const [position,setPosition] = useState(52); return <section className="bg-ink py-24 text-background lg:py-36"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><Eyebrow light>Featured Work</Eyebrow><div className="mb-12 grid gap-7 lg:grid-cols-2"><Heading light>From Vision<br />To Finished Space.</Heading><div className="self-end"><p className="text-xs font-bold uppercase tracking-[0.15em] text-primary">Complete Home Renovation</p><p className="mt-4 max-w-lg leading-7 text-background/60">A dated interior reimagined as a calm, open home with a modern kitchen, natural materials, and purposeful details.</p></div></div><div className="relative h-[60vw] max-h-[720px] min-h-[420px] overflow-hidden select-none"><img src={images.foundation} alt="Home renovation before completion" className="absolute inset-0 size-full object-cover" loading="lazy" /><div className="absolute inset-y-0 left-0 overflow-hidden" style={{ width: `${position}%` }}><img src={images.kitchen} alt="Completed modern home renovation" className="h-full max-w-none object-cover" style={{ width: "calc(100vw - 40px)", maxWidth: "1360px" }} loading="lazy" /></div><div className="absolute inset-y-0 w-px bg-background" style={{ left: `${position}%` }}><span className="absolute left-1/2 top-1/2 grid size-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-primary text-primary-foreground">↔</span></div><input aria-label="Compare before and after renovation" type="range" min="10" max="90" value={position} onChange={(e) => setPosition(Number(e.target.value))} className="absolute inset-0 size-full cursor-ew-resize opacity-0" /><span className="absolute bottom-4 left-4 bg-ink/75 px-3 py-2 text-[10px] font-bold uppercase tracking-widest">After</span><span className="absolute bottom-4 right-4 bg-ink/75 px-3 py-2 text-[10px] font-bold uppercase tracking-widest">Before</span></div></div></section>; }

function WhyUs() { const benefits = [["01","Quality Craftsmanship","Every project receives our full attention to detail and commitment to excellent service."],["02","Foundation Specialists","Expert solutions that help protect your home’s structural integrity."],["03","Complete Home Services","From flooring to finishing, we manage every aspect of your renovation."],["04","Family-Owned Business","Personal service and accountability for your most important investment."]] as const; return <section className="grid bg-background lg:grid-cols-2"><img src={images.detail} alt="Modern completed home exterior" className="h-[520px] size-full object-cover lg:h-full" loading="lazy" /><div className="px-5 py-24 lg:px-16 lg:py-28"><Eyebrow>Why Choose Us</Eyebrow><Heading>Experience Matters.<br />Details Matter More.</Heading><div className="mt-12">{benefits.map(([n,t,d]) => <div key={n} className="grid grid-cols-[auto_1fr] gap-5 border-t border-border py-6"><span className="text-xs font-bold text-primary">{n}</span><div><h3 className="text-lg font-bold">{t}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{d}</p></div></div>)}</div></div></section>; }

function Gallery() { const items = [[images.kitchen,"Open-plan renovation","md:col-span-2 md:row-span-2"],[images.bathroom,"Modern bath",""],[images.flooring,"Natural flooring",""],[images.painting,"Precision finishing","md:col-span-2"]] as const; return <section className="bg-muted py-24 lg:py-36"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="flex flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><div><Eyebrow>Our Recent Work</Eyebrow><Heading>See The Difference<br />Quality Makes.</Heading></div><Button asChild variant="dark"><Link to="/projects">View All Projects <ArrowRight /></Link></Button></div><div className="mt-14 grid auto-rows-[260px] gap-3 md:grid-cols-4">{items.map(([img,title,span]) => <Link to="/projects" key={title} className={`group relative overflow-hidden bg-ink ${span}`}><img src={img} alt={title} className="size-full object-cover transition duration-500 group-hover:scale-105 group-hover:opacity-60" loading="lazy" /><div className="absolute inset-0 flex items-end bg-gradient-to-t from-ink/80 to-transparent p-6 opacity-0 transition-opacity group-hover:opacity-100"><h3 className="text-xl font-bold text-background">{title}</h3><ArrowRight className="ml-auto text-primary" /></div></Link>)}</div></div></section>; }

function Process() { return <section className="bg-background py-24 lg:py-36"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><Eyebrow>Our Process</Eyebrow><Heading>From First Call<br />To Final Detail.</Heading><div className="relative mt-16 grid gap-0 md:grid-cols-4 before:absolute before:left-0 before:right-0 before:top-4 before:hidden before:h-px before:bg-border md:before:block">{[["01","Consultation"],["02","Planning"],["03","Professional Construction"],["04","Final Walkthrough"]].map(([n,t]) => <div key={n} className="relative border-l border-border pb-10 pl-6 md:border-l-0 md:pl-0 md:pr-8"><span className="relative z-10 inline-grid size-8 place-items-center rounded-full bg-foreground text-[10px] font-bold text-background">{n}</span><h3 className="mt-6 text-xl font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Clear communication, considered decisions, and careful execution at every stage.</p></div>)}</div></div></section>; }

function Testimonials() { return <section className="bg-ink py-24 text-background lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-px bg-line px-5 lg:grid-cols-[1.6fr_1fr] lg:px-10"><article className="bg-ink p-8 md:p-14"><Quote className="size-12 text-primary" /><blockquote className="mt-10 max-w-3xl font-display text-3xl font-semibold leading-snug md:text-5xl">“The attention to detail was exceptional. Every step was communicated clearly, and the finished space exceeded what we imagined.”</blockquote><div className="mt-10 flex items-center justify-between"><div><p className="font-bold">Home Renovation Client</p><p className="text-xs text-background/50">Verified customer</p></div><Stars /></div></article><div className="grid gap-px bg-line"><article className="bg-ink p-8"><p className="leading-7 text-background/70">“Professional, clean, dependable, and truly invested in the quality of the finished work.”</p><div className="mt-8"><Stars /><p className="mt-3 text-xs font-bold uppercase tracking-wider">Residential client</p></div></article><article className="bg-ink p-8"><strong className="font-display text-5xl text-primary">4.7 / 5</strong><p className="mt-3 text-sm text-background/60">Google Reviews</p></article></div></div></section>; }
function Stars() { return <div className="flex gap-1" aria-label="5 out of 5 stars">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-4 fill-primary text-primary" />)}</div>; }

function Emergency() { return <section className="border-y border-primary/25 bg-ink py-16 text-background"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 px-5 lg:flex-row lg:items-center lg:justify-between lg:px-10"><div><Eyebrow light>24/7 Emergency Service</Eyebrow><h2 className="text-4xl font-bold md:text-6xl">Need Help Now?</h2><p className="mt-4 max-w-2xl text-background/60">Our team is available for emergency home improvement services when you need us most.</p></div><div className="flex flex-wrap gap-3"><Button size="lg"><Phone /> Call Now</Button><Button size="lg" variant="inverse" asChild><Link to="/contact">Request Service</Link></Button></div></div></section>; }

function Contact() { const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}; return <section className="bg-background py-24 lg:py-36"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><Eyebrow>Start Your Project</Eyebrow><Heading>Let’s Talk About<br />Your Next Project.</Heading><p className="mt-7 max-w-md leading-7 text-muted-foreground">Contact our team for an estimate, a project question, or a renovation consultation.</p><div className="mt-10 space-y-5 text-sm"><p><strong className="mr-3 text-primary">01</strong> Residential & commercial</p><p><strong className="mr-3 text-primary">02</strong> Free project estimates</p><p><strong className="mr-3 text-primary">03</strong> 24/7 emergency availability</p></div></div>{sent ? <div className="flex min-h-[420px] flex-col items-center justify-center border border-border p-10 text-center"><span className="grid size-14 place-items-center rounded-full bg-primary text-primary-foreground"><Check /></span><h3 className="mt-6 text-3xl font-bold">Request received.</h3><p className="mt-3 text-muted-foreground">Thank you. The team will follow up about your project.</p></div> : <form onSubmit={submit} className="grid gap-x-6 sm:grid-cols-2">{["Name","Phone","Email","Address"].map(f=><label key={f} className="border-b border-border py-5 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{f}<input required={f!=="Address"} type={f==="Email"?"email":f==="Phone"?"tel":"text"} className="mt-3 block w-full bg-transparent text-base font-normal text-foreground outline-none" /></label>)}<label className="border-b border-border py-5 text-[10px] font-bold uppercase tracking-wider text-muted-foreground sm:col-span-2">Service Needed<select className="mt-3 block w-full bg-transparent text-base font-normal text-foreground outline-none"><option>Complete renovation</option><option>Foundation repair</option><option>Flooring installation</option><option>Drywall & painting</option><option>Basement finishing</option><option>Handyman service</option></select></label><label className="border-b border-border py-5 text-[10px] font-bold uppercase tracking-wider text-muted-foreground sm:col-span-2">Project Details<textarea rows={4} className="mt-3 block w-full resize-none bg-transparent text-base font-normal text-foreground outline-none" /></label><Button size="lg" className="mt-8 sm:col-span-2">Request a Free Estimate <ArrowRight /></Button></form>}</div></section>; }

function FAQ() { const qs=[["How long does a typical renovation project take?","Project timing depends on scope, materials, and site conditions. After the consultation, we provide a clear schedule tailored to your renovation."],["Do you provide free estimates?","Yes. Contact our team to discuss your project and arrange a free estimate."],["What areas do you serve?","Service coverage varies by project. Send your address through the estimate form and our team will confirm availability."],["Do you offer emergency services?","Yes, emergency home improvement support is available 24/7."],["Do you handle complete home renovations?","Yes. We manage complete renovations as well as focused upgrades, repairs, and finishing work."],["Are you licensed and insured?","Please contact our team for current licensing and insurance documentation relevant to your project."]] as const; return <section className="bg-muted py-24 lg:py-32"><div className="mx-auto grid max-w-[1200px] gap-12 px-5 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow>FAQ</Eyebrow><Heading>Good Questions.<br />Clear Answers.</Heading></div><Accordion type="single" collapsible>{qs.map(([q,a],i)=><AccordionItem key={q} value={`q-${i}`}><AccordionTrigger className="py-6 text-left font-display text-lg font-bold hover:no-underline">{q}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>; }