import { Link } from "@tanstack/react-router";
import { ArrowRight, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SitePage } from "@/components/site-layout";

type Kind = "about" | "services" | "projects" | "reviews" | "contact";

const pageData = {
  about: { eyebrow: "Established 2014", title: "Built On Skill. Guided By Integrity.", image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=2200&q=85" },
  services: { eyebrow: "Complete Home Improvement", title: "One Team. Every Detail.", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=2200&q=85" },
  projects: { eyebrow: "Selected Work", title: "Spaces Made Better.", image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=2200&q=85" },
  reviews: { eyebrow: "Client Experience", title: "Trust Earned On Every Project.", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2200&q=85" },
  contact: { eyebrow: "Start A Conversation", title: "Let’s Talk About Your Project.", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2200&q=85" },
} as const;

export function InteriorPage({ kind }: { kind: Kind }) {
  const data = pageData[kind];
  return <SitePage {...data}>{kind === "about" ? <About /> : kind === "services" ? <Services /> : kind === "projects" ? <Projects /> : kind === "reviews" ? <Reviews /> : <Contact />}</SitePage>;
}

function Shell({ label, title, children }: { label: string; title: string; children: React.ReactNode }) { return <section className="bg-background py-24 lg:py-32"><div className="mx-auto max-w-[1200px] px-5 lg:px-10"><p className="mb-5 text-[11px] font-bold uppercase tracking-[0.18em] text-primary">{label}</p><h2 className="max-w-4xl text-4xl font-bold leading-tight md:text-6xl">{title}</h2>{children}</div></section>; }

function About() { return <Shell label="Our Standard" title="Professional craftsmanship meets personal accountability."><div className="mt-14 grid gap-10 lg:grid-cols-2"><p className="text-xl leading-8">Progress Interior Designs is a family-owned home improvement company serving homeowners and commercial clients since 2014.</p><div className="space-y-5 text-muted-foreground"><p>We approach every project with clear communication, careful planning, and respect for the space. Our work spans foundation repair, remodeling, flooring, painting, basement finishing, and dependable handyman service.</p><p>The result is a more coordinated experience and work built to last.</p><Button asChild className="mt-4"><Link to="/contact">Discuss Your Project <ArrowRight /></Link></Button></div></div></Shell>; }

function Services() { const list=[["01","Foundation Repair"],["02","General Contracting"],["03","Flooring Installation"],["04","Drywall & Painting"],["05","Basement Finishing"],["06","Handyman Services"]]; return <Shell label="Capabilities" title="Comprehensive expertise, thoughtfully delivered."><div className="mt-16 border-t border-border">{list.map(([n,t])=><div key={n} className="group grid grid-cols-[50px_1fr_auto] items-center border-b border-border py-7"><span className="text-xs font-bold text-primary">{n}</span><h3 className="text-xl font-bold md:text-3xl">{t}</h3><ArrowRight className="transition-transform group-hover:translate-x-2" /></div>)}</div></Shell>; }

function Projects() { const items=[["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80","Complete Home Renovation"],["https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1200&q=80","Bathroom Transformation"],["https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=80","Flooring & Finish Work"],["https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=1200&q=80","Basement Finishing"]]; return <Shell label="Recent Projects" title="A closer look at the work."><div className="mt-14 grid auto-rows-[340px] gap-4 md:grid-cols-2">{items.map(([img,t],i)=><article key={t} className={`group relative overflow-hidden bg-ink ${i===0?"md:row-span-2":""}`}><img src={img} alt={t} className="size-full object-cover transition duration-500 group-hover:scale-105 group-hover:opacity-60" loading="lazy"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-ink p-7 pt-20 text-background"><p className="text-xs uppercase tracking-widest text-primary">Renovation</p><h3 className="mt-2 text-2xl font-bold">{t}</h3></div></article>)}</div></Shell>; }

function Reviews() { const reviews=["The attention to detail was exceptional, and every step was communicated clearly.","Professional, clean, dependable, and truly invested in the finished work.","A reliable team with the experience to handle the project properly."]; return <Shell label="Client Reviews" title="Quality is remembered long after the work is done."><div className="mt-14 grid gap-px bg-border lg:grid-cols-3">{reviews.map((r,i)=><article key={r} className="bg-background p-8"><div className="flex gap-1">{Array.from({length:5}).map((_,n)=><Star key={n} className="size-4 fill-primary text-primary" />)}</div><blockquote className="mt-8 text-xl leading-8">“{r}”</blockquote><p className="mt-8 text-xs font-bold uppercase tracking-wider text-muted-foreground">Verified client {i+1}</p></article>)}</div></Shell>; }

function Contact() { return <Shell label="Free Estimate" title="Tell us what you want to improve."><div className="mt-14 grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="leading-7 text-muted-foreground">Contact the team for an estimate, project question, or emergency service request.</p><div className="mt-8 border-l-2 border-primary pl-5"><strong className="block">24/7 Emergency Service</strong><span className="text-sm text-muted-foreground">Help when you need it most.</span></div></div><form className="grid gap-6 sm:grid-cols-2" onSubmit={(e)=>e.preventDefault()}>{["Name","Phone","Email","Address"].map(x=><label key={x} className="border-b border-border pb-3 text-xs font-bold uppercase tracking-wider">{x}<input required className="mt-3 block w-full bg-transparent text-base font-normal outline-none" /></label>)}<label className="border-b border-border pb-3 text-xs font-bold uppercase tracking-wider sm:col-span-2">Message<textarea rows={5} className="mt-3 block w-full resize-none bg-transparent text-base font-normal outline-none" /></label><Button size="lg" className="sm:col-span-2">Request a Free Estimate <ArrowRight /></Button></form></div></Shell>; }