/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesBasementFinishingRouteImport } from './routes/services/basement-finishing'
import { Route as ServicesBathroomRemodelingRouteImport } from './routes/services/bathroom-remodeling'
import { Route as ServicesCustomMillworkRouteImport } from './routes/services/custom-millwork'
import { Route as ServicesDrywallPaintingRouteImport } from './routes/services/drywall-painting'
import { Route as ServicesFlooringRouteImport } from './routes/services/flooring'
import { Route as ServicesFoundationRepairRouteImport } from './routes/services/foundation-repair'
import { Route as ServicesKitchenRemodelingRouteImport } from './routes/services/kitchen-remodeling'
import { Route as ServicesWholeHomeRenovationRouteImport } from './routes/services/whole-home-renovation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBasementFinishingRoute =
  ServicesBasementFinishingRouteImport.update({
    id: '/services/basement-finishing',
    path: '/services/basement-finishing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBathroomRemodelingRoute =
  ServicesBathroomRemodelingRouteImport.update({
    id: '/services/bathroom-remodeling',
    path: '/services/bathroom-remodeling',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomMillworkRoute = ServicesCustomMillworkRouteImport.update({
  id: '/services/custom-millwork',
  path: '/services/custom-millwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDrywallPaintingRoute = ServicesDrywallPaintingRouteImport.update({
  id: '/services/drywall-painting',
  path: '/services/drywall-painting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFlooringRoute = ServicesFlooringRouteImport.update({
  id: '/services/flooring',
  path: '/services/flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFoundationRepairRoute =
  ServicesFoundationRepairRouteImport.update({
    id: '/services/foundation-repair',
    path: '/services/foundation-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesKitchenRemodelingRoute =
  ServicesKitchenRemodelingRouteImport.update({
    id: '/services/kitchen-remodeling',
    path: '/services/kitchen-remodeling',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWholeHomeRenovationRoute =
  ServicesWholeHomeRenovationRouteImport.update({
    id: '/services/whole-home-renovation',
    path: '/services/whole-home-renovation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services/basement-finishing': typeof ServicesBasementFinishingRoute
  '/services/bathroom-remodeling': typeof ServicesBathroomRemodelingRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/drywall-painting': typeof ServicesDrywallPaintingRoute
  '/services/flooring': typeof ServicesFlooringRoute
  '/services/foundation-repair': typeof ServicesFoundationRepairRoute
  '/services/kitchen-remodeling': typeof ServicesKitchenRemodelingRoute
  '/services/whole-home-renovation': typeof ServicesWholeHomeRenovationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services/basement-finishing': typeof ServicesBasementFinishingRoute
  '/services/bathroom-remodeling': typeof ServicesBathroomRemodelingRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/drywall-painting': typeof ServicesDrywallPaintingRoute
  '/services/flooring': typeof ServicesFlooringRoute
  '/services/foundation-repair': typeof ServicesFoundationRepairRoute
  '/services/kitchen-remodeling': typeof ServicesKitchenRemodelingRoute
  '/services/whole-home-renovation': typeof ServicesWholeHomeRenovationRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/projects': typeof ProjectsRoute
  '/reviews': typeof ReviewsRoute
  '/services/basement-finishing': typeof ServicesBasementFinishingRoute
  '/services/bathroom-remodeling': typeof ServicesBathroomRemodelingRoute
  '/services/custom-millwork': typeof ServicesCustomMillworkRoute
  '/services/drywall-painting': typeof ServicesDrywallPaintingRoute
  '/services/flooring': typeof ServicesFlooringRoute
  '/services/foundation-repair': typeof ServicesFoundationRepairRoute
  '/services/kitchen-remodeling': typeof ServicesKitchenRemodelingRoute
  '/services/whole-home-renovation': typeof ServicesWholeHomeRenovationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/projects'
    | '/reviews'
    | '/services/basement-finishing'
    | '/services/bathroom-remodeling'
    | '/services/custom-millwork'
    | '/services/drywall-painting'
    | '/services/flooring'
    | '/services/foundation-repair'
    | '/services/kitchen-remodeling'
    | '/services/whole-home-renovation'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/projects'
    | '/reviews'
    | '/services/basement-finishing'
    | '/services/bathroom-remodeling'
    | '/services/custom-millwork'
    | '/services/drywall-painting'
    | '/services/flooring'
    | '/services/foundation-repair'
    | '/services/kitchen-remodeling'
    | '/services/whole-home-renovation'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/estimate'
    | '/projects'
    | '/reviews'
    | '/services/basement-finishing'
    | '/services/bathroom-remodeling'
    | '/services/custom-millwork'
    | '/services/drywall-painting'
    | '/services/flooring'
    | '/services/foundation-repair'
    | '/services/kitchen-remodeling'
    | '/services/whole-home-renovation'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EstimateRoute: typeof EstimateRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesBasementFinishingRoute: typeof ServicesBasementFinishingRoute
  ServicesBathroomRemodelingRoute: typeof ServicesBathroomRemodelingRoute
  ServicesCustomMillworkRoute: typeof ServicesCustomMillworkRoute
  ServicesDrywallPaintingRoute: typeof ServicesDrywallPaintingRoute
  ServicesFlooringRoute: typeof ServicesFlooringRoute
  ServicesFoundationRepairRoute: typeof ServicesFoundationRepairRoute
  ServicesKitchenRemodelingRoute: typeof ServicesKitchenRemodelingRoute
  ServicesWholeHomeRenovationRoute: typeof ServicesWholeHomeRenovationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/basement-finishing': {
      id: '/services/basement-finishing'
      path: '/services/basement-finishing'
      fullPath: '/services/basement-finishing'
      preLoaderRoute: typeof ServicesBasementFinishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bathroom-remodeling': {
      id: '/services/bathroom-remodeling'
      path: '/services/bathroom-remodeling'
      fullPath: '/services/bathroom-remodeling'
      preLoaderRoute: typeof ServicesBathroomRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-millwork': {
      id: '/services/custom-millwork'
      path: '/services/custom-millwork'
      fullPath: '/services/custom-millwork'
      preLoaderRoute: typeof ServicesCustomMillworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/drywall-painting': {
      id: '/services/drywall-painting'
      path: '/services/drywall-painting'
      fullPath: '/services/drywall-painting'
      preLoaderRoute: typeof ServicesDrywallPaintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/flooring': {
      id: '/services/flooring'
      path: '/services/flooring'
      fullPath: '/services/flooring'
      preLoaderRoute: typeof ServicesFlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/foundation-repair': {
      id: '/services/foundation-repair'
      path: '/services/foundation-repair'
      fullPath: '/services/foundation-repair'
      preLoaderRoute: typeof ServicesFoundationRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kitchen-remodeling': {
      id: '/services/kitchen-remodeling'
      path: '/services/kitchen-remodeling'
      fullPath: '/services/kitchen-remodeling'
      preLoaderRoute: typeof ServicesKitchenRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/whole-home-renovation': {
      id: '/services/whole-home-renovation'
      path: '/services/whole-home-renovation'
      fullPath: '/services/whole-home-renovation'
      preLoaderRoute: typeof ServicesWholeHomeRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EstimateRoute: EstimateRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesBasementFinishingRoute: ServicesBasementFinishingRoute,
  ServicesBathroomRemodelingRoute: ServicesBathroomRemodelingRoute,
  ServicesCustomMillworkRoute: ServicesCustomMillworkRoute,
  ServicesDrywallPaintingRoute: ServicesDrywallPaintingRoute,
  ServicesFlooringRoute: ServicesFlooringRoute,
  ServicesFoundationRepairRoute: ServicesFoundationRepairRoute,
  ServicesKitchenRemodelingRoute: ServicesKitchenRemodelingRoute,
  ServicesWholeHomeRenovationRoute: ServicesWholeHomeRenovationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
